-- CREATE TABLE todos (
--     id SERIAL PRIMARY KEY,
--     title VARCHAR(255) NOT NULL,
--     is_completed BOOLEAN NOT NULL DEFAULT FALSE,
--     created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
-- );


